### ISSUE TITLE
Vous avez tous ecrit vos phrases ?

### ISSUE THREAD

**Issue by arimoussa** [PolytechLyon/git-5a-g1-team_tim#1]

**Comment by sofianebelaribi** [comment]
mais pull push pour que je puisse la continuer

**Comment by ajk11** [comment]
Ecrit sur le fichier de soso là

**Comment by ajk11** [comment]
Et modifie le directement dessus
pas la peine de pull push de saaay moort

**Comment by sofianebelaribi** [comment]
fais git pull
tu ecris sur story.md
et tu git add .
git commit"partie moussa"
git push

**Comment by RaphaelMARIENELLY** [comment]
j'ecris mon fichier sur github, pas besoin de pull et push, c est des commit

**Comment by sofianebelaribi** [comment]
oui dans le pire des cas faut juste que moussa commence
@arimoussa
